Prepare to distribution

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,9 +5,9 @@ on:
     branches: [ ]
   push:
     branches: [ ]
-#  create:
-#      tags: ['v*'] # Push events to matching v*, i.e. v1.0, v20.15.10
-# https://openframeworks.cc/ci_server/versions/nightly/of_v20230223_osx_nightly.zip
+  create:
+      tags: ['v*'] # Push events to matching v*, i.e. v1.0, v20.15.10
+
 env:
   pkgname: BrainwaveOSC
 jobs:
@@ -26,26 +26,26 @@ jobs:
         shell: ${{matrix.shell}}
 
     steps:
-#    - name: Install the Apple certificate and provisioning profile
-#      if: ${{runner.os == 'macOS'}}
-#      env:
-#          P12_CERTIFICATE_BASE64: ${{ secrets.P12_CERTIFICATE_BASE64 }}
-#          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
-#          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-#      run: |
-#          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-#          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-#          echo "IDENTITY_NAME=donarturo11.github.io" >> $GITHUB_ENV
-#          echo -n "$P12_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-#          echo "::notice:: decode certificate succeed"
-#          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-#          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-#          security default-keychain -s $KEYCHAIN_PATH
-#          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-#          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH -T /usr/bin/codesign -T /usr/bin/productsign || echo "::warning:: Import certificate failed"
-#          security list-keychain -d user -s $KEYCHAIN_PATH || echo "::warning:: List keychain failed"
-#          security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
-#          security find-identity || echo "::warning:: List keychain failed"
+    - name: Install the Apple certificate and provisioning profile
+      if: ${{runner.os == 'macOS'}}
+      env:
+          P12_CERTIFICATE_BASE64: ${{ secrets.P12_CERTIFICATE_BASE64 }}
+          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+      run: |
+          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          echo "IDENTITY_NAME=donarturo11.github.io" >> $GITHUB_ENV
+          echo -n "$P12_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
+          echo "::notice:: decode certificate succeed"
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security default-keychain -s $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH -T /usr/bin/codesign -T /usr/bin/productsign || echo "::warning:: Import certificate failed"
+          security list-keychain -d user -s $KEYCHAIN_PATH || echo "::warning:: List keychain failed"
+          security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
+          security find-identity || echo "::warning:: List keychain failed"
           
     - if: ${{runner.os == 'Windows'}}
       name: Install MinGW
@@ -180,7 +180,7 @@ jobs:
           hdiutil attach temp.dmg
           TEMPDMG=${PWD}/temp.dmg
           cd ${BUILD_DIR}/bin
-          codesign --verbose --strict --continue --timestamp --force --deep -s- *.app
+          codesign --verbose --strict --continue --timestamp --force --deep -s ${IDENTITY_NAME} *.app
           cp -av * /Volumes/${PACKAGE_NAME}
           ln -s /Applications/ /Volumes/${PACKAGE_NAME}/Applications
           hdiutil detach /Volumes/${PACKAGE_NAME}
